webmiss/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns=[
	# /music/
	url(r'^$',views.index,name='index'),
	
	#/music/<album_id>/
	url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),
	
	
	url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite, name='favorite'),
]

webmiss/webmiss/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

webmiss/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)
	
	def __str__(self):
		return self.album_title + " - " + self.artist
		
class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)
	def __str__(self):
		return self.song_title

webmiss/music/views.py
from django.http import HttpResponse, Http404
#from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

'''
def index(request):
	all_album = Album.objects.all()
	html=''
	for album in all_album:
		url = '/music/'+ str(album.id) + '/'
		html += '<a href="'+ url + '">'+ album.album_title+'</a><br>'
	return HttpResponse(html)

def index(request):
	all_album = Album.objects.all()
	template = loader.get_template('music/index.html')
	context = {
		'all_album' : all_album,
	}
	return HttpResponse(template.render(context,request))
'''
def index(request):
	all_album = Album.objects.all()
	return render(request, 'music/index.html',{ 'all_album' : all_album})

def detail(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	return render(request, 'music/detail.html',{'album':album})

def favorite(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	try:
		selected_song=album.song_set.get(pk=request.POST['song'])
	except(KeyError, Song.DoesNotExist):
		return render(request, 'music/detail.html',{	'album':album,
			'error_message':"You did not select a valid song"
		})
	else:
		selected_song.is_favorite = True
		selected_song.save()
		return render(request,'music/detail.html',{'album':album})
'''return HttpResponse('<h2>Album id is ' + str(album_id) +'</h2>') 
 try:
		album = Album.objects.get(pk=album_id)
	except Album.DoesNotExist:
		raise Http404("Album does not exist")'''
	

webmiss/music/templates/music/detail.html
<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>
<!--<ul>
	{% for song in album.song_set.all %}
		<li>{{ song.song_title }}.{{song.file_type}}</li>
	{% endfor %}
</ul>-->
{% if error_message %}
	<p><strong>{{ error_message}}</strong><p>
{% endif %}
<form action="{% url 'music:favorite' album.id %}" method='post'>
	{% csrf_token %}
	{% for song in album.song_set.all %}
		<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{song.id}}"/>
		<label for="song{{forloop.counter}}">
			{{ song.song_title }}
			{% if song.is_favorite %}
				<img src="https://hansons-lansing.com/images/layout01/favicon.ico"/>
			{% endif %}
		</label><br>
	{% endfor %}
	<input type="submit" value="Favorite">
</form>

webmiss/music/templates/music/index.html
<!-- Load your paths to static file-->
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- header -->
		<div class="navbar-header" >
			<button type="button" class="navbar-toggle" data-toggle=collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
		</div>	
		
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
						Albums
					</a>
				</li>	
				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
						Songs
					</a>
				</li>	
			</ul>
		</div>
		
	</div>
</nav>	

{% if all_album %}
	<h2>List of Albums</h2>
	<ul>
		{% for album in all_album %}
		<!--<li><a href="/music/{{ album.id }}/"><h4>{{ album.album_title }}</h4></a></li>-->
		<li><a href="{% url 'music:detail' album.id %}"><h4>{{ album.album_title }}</h4></a></li>
		{% endfor %}
	</ul>
{% else %}
	<h3>You don't have any albums</h3>
{% endif %}